## Gradle Settings
org.gradle.jvmargs = -Xmx4G -Xms4G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true

fabric.loom.disableProjectDependentMods = true

## Mod Info
archives_base_name = interiors
mod_version=0.5.6
maven_group = com.sudolev

### Version Specific Dependencies
minecraft_version = 1.21.1

## Mappings
# https://lambdaurora.dev/tools/import_quilt.html
qm_version = 9
# https://parchmentmc.org/docs/getting-started
parchment_version = 2024.11.17

# Fabric - https://fabricmc.net/develop/
fabric_loader_version = 0.16.9
fabric_api_version = 0.105.0

# NeoForge - https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 21.1.192

## Create
# Fabric (no usado en 1.21.1; referencial)
create_fabric_version = 6.0.9-171
# https://maven.createmod.net/com/simibubi/create/create-1.21.1/
create_neoforge_version = 6.0.9-171
registrate_version = MC1.21-1.3.0+62
mixin_extras_version = 0.4.1
ponder_version = 1.1.1
flywheel_version = 1.1.0

## Fabric Mods
# https://modrinth.com/mod/lazydfu/versions
lazydfu_version = 0.1.3
# https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.2.2
# Better Mods Button - https://www.curseforge.com/minecraft/mc-mods/better-mods-button/files
bmb = 4613425
# Catalogue - https://www.curseforge.com/minecraft/mc-mods/catalogue/files
catalogue = 4590890
